/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActionsRouteImport } from './routes/actions'
import { Route as BenchRouteImport } from './routes/bench'
import { Route as CandidatesRouteImport } from './routes/candidates'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as ExternalHiringRouteImport } from './routes/external-hiring'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FraudDetectionRouteImport } from './routes/fraud-detection'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as InternalHiringRouteImport } from './routes/internal-hiring'
import { Route as JobAnalysisRouteImport } from './routes/job-analysis'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ScreeningRouteImport } from './routes/screening'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as AtsBenchmarkIndexRouteImport } from './routes/ats-benchmark/index'
import { Route as HandoffIndexRouteImport } from './routes/handoff/index'
import { Route as HandoffHandoffIdRouteImport } from './routes/handoff/$handoffId'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as TalentMarketplaceIndexRouteImport } from './routes/talent-marketplace/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionsRoute = ActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchRoute = BenchRouteImport.update({
  id: '/bench',
  path: '/bench',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesRoute = CandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const ExternalHiringRoute = ExternalHiringRouteImport.update({
  id: '/external-hiring',
  path: '/external-hiring',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FraudDetectionRoute = FraudDetectionRouteImport.update({
  id: '/fraud-detection',
  path: '/fraud-detection',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const InternalHiringRoute = InternalHiringRouteImport.update({
  id: '/internal-hiring',
  path: '/internal-hiring',
  getParentRoute: () => rootRouteImport,
} as any)
const JobAnalysisRoute = JobAnalysisRouteImport.update({
  id: '/job-analysis',
  path: '/job-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreeningRoute = ScreeningRouteImport.update({
  id: '/screening',
  path: '/screening',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const AtsBenchmarkIndexRoute = AtsBenchmarkIndexRouteImport.update({
  id: '/ats-benchmark/',
  path: '/ats-benchmark/',
  getParentRoute: () => rootRouteImport,
} as any)
const HandoffIndexRoute = HandoffIndexRouteImport.update({
  id: '/handoff/',
  path: '/handoff/',
  getParentRoute: () => rootRouteImport,
} as any)
const HandoffHandoffIdRoute = HandoffHandoffIdRouteImport.update({
  id: '/handoff/$handoffId',
  path: '/handoff/$handoffId',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentMarketplaceIndexRoute = TalentMarketplaceIndexRouteImport.update({
  id: '/talent-marketplace/',
  path: '/talent-marketplace/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/bench': typeof BenchRoute
  '/candidates': typeof CandidatesRoute
  '/compare': typeof CompareRoute
  '/external-hiring': typeof ExternalHiringRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/fraud-detection': typeof FraudDetectionRoute
  '/insights': typeof InsightsRoute
  '/internal-hiring': typeof InternalHiringRoute
  '/job-analysis': typeof JobAnalysisRoute
  '/login': typeof LoginRoute
  '/network': typeof NetworkRoute
  '/ops': typeof OpsRoute
  '/people': typeof PeopleRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/screening': typeof ScreeningRoute
  '/settings': typeof SettingsRoute
  '/upload': typeof UploadRoute
  '/welcome': typeof WelcomeRoute
  '/handoff/$handoffId': typeof HandoffHandoffIdRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/ats-benchmark/': typeof AtsBenchmarkIndexRoute
  '/handoff/': typeof HandoffIndexRoute
  '/talent-marketplace/': typeof TalentMarketplaceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/bench': typeof BenchRoute
  '/candidates': typeof CandidatesRoute
  '/compare': typeof CompareRoute
  '/external-hiring': typeof ExternalHiringRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/fraud-detection': typeof FraudDetectionRoute
  '/insights': typeof InsightsRoute
  '/internal-hiring': typeof InternalHiringRoute
  '/job-analysis': typeof JobAnalysisRoute
  '/login': typeof LoginRoute
  '/network': typeof NetworkRoute
  '/ops': typeof OpsRoute
  '/people': typeof PeopleRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/screening': typeof ScreeningRoute
  '/settings': typeof SettingsRoute
  '/upload': typeof UploadRoute
  '/welcome': typeof WelcomeRoute
  '/handoff/$handoffId': typeof HandoffHandoffIdRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/ats-benchmark': typeof AtsBenchmarkIndexRoute
  '/handoff': typeof HandoffIndexRoute
  '/talent-marketplace': typeof TalentMarketplaceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actions': typeof ActionsRoute
  '/bench': typeof BenchRoute
  '/candidates': typeof CandidatesRoute
  '/compare': typeof CompareRoute
  '/external-hiring': typeof ExternalHiringRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/fraud-detection': typeof FraudDetectionRoute
  '/insights': typeof InsightsRoute
  '/internal-hiring': typeof InternalHiringRoute
  '/job-analysis': typeof JobAnalysisRoute
  '/login': typeof LoginRoute
  '/network': typeof NetworkRoute
  '/ops': typeof OpsRoute
  '/people': typeof PeopleRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/screening': typeof ScreeningRoute
  '/settings': typeof SettingsRoute
  '/upload': typeof UploadRoute
  '/welcome': typeof WelcomeRoute
  '/handoff/$handoffId': typeof HandoffHandoffIdRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/ats-benchmark/': typeof AtsBenchmarkIndexRoute
  '/handoff/': typeof HandoffIndexRoute
  '/talent-marketplace/': typeof TalentMarketplaceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actions'
    | '/bench'
    | '/candidates'
    | '/compare'
    | '/external-hiring'
    | '/forgot-password'
    | '/fraud-detection'
    | '/insights'
    | '/internal-hiring'
    | '/job-analysis'
    | '/login'
    | '/network'
    | '/ops'
    | '/people'
    | '/register'
    | '/reset-password'
    | '/screening'
    | '/settings'
    | '/upload'
    | '/welcome'
    | '/handoff/$handoffId'
    | '/jobs/$jobId'
    | '/ats-benchmark/'
    | '/handoff/'
    | '/talent-marketplace/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actions'
    | '/bench'
    | '/candidates'
    | '/compare'
    | '/external-hiring'
    | '/forgot-password'
    | '/fraud-detection'
    | '/insights'
    | '/internal-hiring'
    | '/job-analysis'
    | '/login'
    | '/network'
    | '/ops'
    | '/people'
    | '/register'
    | '/reset-password'
    | '/screening'
    | '/settings'
    | '/upload'
    | '/welcome'
    | '/handoff/$handoffId'
    | '/jobs/$jobId'
    | '/ats-benchmark'
    | '/handoff'
    | '/talent-marketplace'
  id:
    | '__root__'
    | '/'
    | '/actions'
    | '/bench'
    | '/candidates'
    | '/compare'
    | '/external-hiring'
    | '/forgot-password'
    | '/fraud-detection'
    | '/insights'
    | '/internal-hiring'
    | '/job-analysis'
    | '/login'
    | '/network'
    | '/ops'
    | '/people'
    | '/register'
    | '/reset-password'
    | '/screening'
    | '/settings'
    | '/upload'
    | '/welcome'
    | '/handoff/$handoffId'
    | '/jobs/$jobId'
    | '/ats-benchmark/'
    | '/handoff/'
    | '/talent-marketplace/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActionsRoute: typeof ActionsRoute
  BenchRoute: typeof BenchRoute
  CandidatesRoute: typeof CandidatesRoute
  CompareRoute: typeof CompareRoute
  ExternalHiringRoute: typeof ExternalHiringRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  FraudDetectionRoute: typeof FraudDetectionRoute
  InsightsRoute: typeof InsightsRoute
  InternalHiringRoute: typeof InternalHiringRoute
  JobAnalysisRoute: typeof JobAnalysisRoute
  LoginRoute: typeof LoginRoute
  NetworkRoute: typeof NetworkRoute
  OpsRoute: typeof OpsRoute
  PeopleRoute: typeof PeopleRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ScreeningRoute: typeof ScreeningRoute
  SettingsRoute: typeof SettingsRoute
  UploadRoute: typeof UploadRoute
  WelcomeRoute: typeof WelcomeRoute
  HandoffHandoffIdRoute: typeof HandoffHandoffIdRoute
  JobsJobIdRoute: typeof JobsJobIdRoute
  AtsBenchmarkIndexRoute: typeof AtsBenchmarkIndexRoute
  HandoffIndexRoute: typeof HandoffIndexRoute
  TalentMarketplaceIndexRoute: typeof TalentMarketplaceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actions': {
      id: '/actions'
      path: '/actions'
      fullPath: '/actions'
      preLoaderRoute: typeof ActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bench': {
      id: '/bench'
      path: '/bench'
      fullPath: '/bench'
      preLoaderRoute: typeof BenchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates': {
      id: '/candidates'
      path: '/candidates'
      fullPath: '/candidates'
      preLoaderRoute: typeof CandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/external-hiring': {
      id: '/external-hiring'
      path: '/external-hiring'
      fullPath: '/external-hiring'
      preLoaderRoute: typeof ExternalHiringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fraud-detection': {
      id: '/fraud-detection'
      path: '/fraud-detection'
      fullPath: '/fraud-detection'
      preLoaderRoute: typeof FraudDetectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/internal-hiring': {
      id: '/internal-hiring'
      path: '/internal-hiring'
      fullPath: '/internal-hiring'
      preLoaderRoute: typeof InternalHiringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-analysis': {
      id: '/job-analysis'
      path: '/job-analysis'
      fullPath: '/job-analysis'
      preLoaderRoute: typeof JobAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screening': {
      id: '/screening'
      path: '/screening'
      fullPath: '/screening'
      preLoaderRoute: typeof ScreeningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ats-benchmark/': {
      id: '/ats-benchmark/'
      path: '/ats-benchmark'
      fullPath: '/ats-benchmark/'
      preLoaderRoute: typeof AtsBenchmarkIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handoff/': {
      id: '/handoff/'
      path: '/handoff'
      fullPath: '/handoff/'
      preLoaderRoute: typeof HandoffIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handoff/$handoffId': {
      id: '/handoff/$handoffId'
      path: '/handoff/$handoffId'
      fullPath: '/handoff/$handoffId'
      preLoaderRoute: typeof HandoffHandoffIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent-marketplace/': {
      id: '/talent-marketplace/'
      path: '/talent-marketplace'
      fullPath: '/talent-marketplace/'
      preLoaderRoute: typeof TalentMarketplaceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActionsRoute: ActionsRoute,
  BenchRoute: BenchRoute,
  CandidatesRoute: CandidatesRoute,
  CompareRoute: CompareRoute,
  ExternalHiringRoute: ExternalHiringRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  FraudDetectionRoute: FraudDetectionRoute,
  InsightsRoute: InsightsRoute,
  InternalHiringRoute: InternalHiringRoute,
  JobAnalysisRoute: JobAnalysisRoute,
  LoginRoute: LoginRoute,
  NetworkRoute: NetworkRoute,
  OpsRoute: OpsRoute,
  PeopleRoute: PeopleRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ScreeningRoute: ScreeningRoute,
  SettingsRoute: SettingsRoute,
  UploadRoute: UploadRoute,
  WelcomeRoute: WelcomeRoute,
  HandoffHandoffIdRoute: HandoffHandoffIdRoute,
  JobsJobIdRoute: JobsJobIdRoute,
  AtsBenchmarkIndexRoute: AtsBenchmarkIndexRoute,
  HandoffIndexRoute: HandoffIndexRoute,
  TalentMarketplaceIndexRoute: TalentMarketplaceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
